/**
 * Mock Data System for SneakerGram
 * Instagram-like demo data with more profiles and conversations
 */

import {
  User,
  Sneaker,
  Post,
  Listing,
  Conversation,
  Message,
  Notification,
  Service,
  PostType,
  ListingType,
  ListingStatus,
  VerificationLevel,
  MessageType,
  NotificationType,
  ServiceCategory,
  SneakerCategory,
} from '@/types';
import { BEST_SNEAKER_IMAGES } from './bestImages';

function getRandomPastDate(daysAgo: number): Date {
  const now = new Date();
  const randomDays = Math.floor(Math.random() * daysAgo);
  return new Date(now.getTime() - randomDays * 24 * 60 * 60 * 1000);
}

function getRandomMinutesAgo(minutes: number): Date {
  return new Date(Date.now() - Math.floor(Math.random() * minutes) * 60 * 1000);
}

// Avatar URLs using DiceBear
const avatarSeeds = [
  'Felix', 'Aneka', 'Jasmine', 'Max', 'Sophie', 'Oliver', 'Emma', 'Lucas',
  'Mia', 'Noah', 'Ava', 'Liam', 'Isabella', 'Mason', 'Charlotte', 'Ethan',
  'Amelia', 'James', 'Harper', 'Benjamin', 'Evelyn', 'Alexander', 'Abigail', 'Daniel'
];

const getAvatar = (seed: string) => `https://api.dicebear.com/7.x/avataaars/svg?seed=${seed}`;


// Generate 20 Mock Users for Instagram-like experience
export const mockUsers: User[] = [
  {
    id: 'user-1',
    username: 'sneakerhead_mike',
    displayName: 'Mike Johnson',
    email: 'mike@sneakergram.com',
    avatar: getAvatar(avatarSeeds[0]),
    bio: 'Jordan collector since 2010 👟 | NYC',
    shoeSize: '10.5',
    verified: true,
    verificationLevel: VerificationLevel.GOLD,
    followers: 15420,
    following: 892,
    collection: ['sneaker-1', 'sneaker-2', 'sneaker-5'],
    wishlist: ['sneaker-10', 'sneaker-12'],
    createdAt: new Date('2022-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'user-2',
    username: 'kickz_queen',
    displayName: 'Sarah Chen',
    email: 'sarah@sneakergram.com',
    avatar: getAvatar(avatarSeeds[1]),
    bio: 'Sneaker enthusiast | Dunk collector 🗽',
    shoeSize: '8',
    verified: true,
    verificationLevel: VerificationLevel.ID,
    followers: 8934,
    following: 456,
    collection: ['sneaker-3', 'sneaker-4'],
    wishlist: ['sneaker-7'],
    createdAt: new Date('2022-03-20'),
    updatedAt: new Date('2024-01-14'),
  },
  {
    id: 'user-3',
    username: 'yeezy_fanatic',
    displayName: 'Alex Rodriguez',
    email: 'alex@sneakergram.com',
    avatar: getAvatar(avatarSeeds[2]),
    bio: 'Yeezy collector | DM for trades',
    shoeSize: '11',
    verified: true,
    verificationLevel: VerificationLevel.EMAIL,
    followers: 5621,
    following: 234,
    collection: ['sneaker-11', 'sneaker-13'],
    wishlist: ['sneaker-1'],
    createdAt: new Date('2022-06-10'),
    updatedAt: new Date('2024-01-13'),
  },
  {
    id: 'user-4',
    username: 'retro_runner',
    displayName: 'James Wilson',
    email: 'james@sneakergram.com',
    avatar: getAvatar(avatarSeeds[3]),
    bio: 'Vintage sneaker restoration 🔧',
    shoeSize: '9.5',
    verified: false,
    verificationLevel: VerificationLevel.EMAIL,
    followers: 3245,
    following: 567,
    collection: ['sneaker-15', 'sneaker-16'],
    wishlist: ['sneaker-18'],
    createdAt: new Date('2022-08-22'),
    updatedAt: new Date('2024-01-12'),
  },
  {
    id: 'user-5',
    username: 'sole_collector',
    displayName: 'Emily Davis',
    email: 'emily@sneakergram.com',
    avatar: getAvatar(avatarSeeds[4]),
    bio: 'Sneaker photography | Air Max lover 🌴',
    shoeSize: '7.5',
    verified: true,
    verificationLevel: VerificationLevel.ID,
    followers: 12890,
    following: 1023,
    collection: ['sneaker-19', 'sneaker-20'],
    wishlist: ['sneaker-22'],
    createdAt: new Date('2021-11-05'),
    updatedAt: new Date('2024-01-11'),
  },
  {
    id: 'user-6',
    username: 'dunk_master',
    displayName: 'Chris Martinez',
    email: 'chris@sneakergram.com',
    avatar: getAvatar(avatarSeeds[5]),
    bio: 'SB Dunk collector | Skater 🛹',
    shoeSize: '10',
    verified: false,
    verificationLevel: VerificationLevel.EMAIL,
    followers: 4567,
    following: 789,
    collection: ['sneaker-24', 'sneaker-25'],
    wishlist: ['sneaker-26'],
    createdAt: new Date('2023-01-18'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    id: 'user-7',
    username: 'boost_life',
    displayName: 'Taylor Brown',
    email: 'taylor@sneakergram.com',
    avatar: getAvatar(avatarSeeds[6]),
    bio: 'Ultraboost enthusiast | Runner 🏃',
    shoeSize: '9',
    verified: true,
    verificationLevel: VerificationLevel.GOLD,
    followers: 9876,
    following: 432,
    collection: ['sneaker-27', 'sneaker-28'],
    wishlist: ['sneaker-29'],
    createdAt: new Date('2022-04-12'),
    updatedAt: new Date('2024-01-09'),
  },
  {
    id: 'user-8',
    username: 'classic_kicks',
    displayName: 'Jordan Lee',
    email: 'jordan@sneakergram.com',
    avatar: getAvatar(avatarSeeds[7]),
    bio: 'Converse & Vans collector',
    shoeSize: '8.5',
    verified: false,
    verificationLevel: VerificationLevel.EMAIL,
    followers: 2134,
    following: 345,
    collection: ['sneaker-30', 'sneaker-31'],
    wishlist: ['sneaker-32'],
    createdAt: new Date('2023-02-28'),
    updatedAt: new Date('2024-01-08'),
  },
  {
    id: 'user-9',
    username: 'hype_beast',
    displayName: 'Marcus Thompson',
    email: 'marcus@sneakergram.com',
    avatar: getAvatar(avatarSeeds[8]),
    bio: 'Hype releases only | Miami 🌊',
    shoeSize: '11.5',
    verified: true,
    verificationLevel: VerificationLevel.ID,
    followers: 18234,
    following: 234,
    collection: ['sneaker-33', 'sneaker-34'],
    wishlist: ['sneaker-35'],
    createdAt: new Date('2021-09-14'),
    updatedAt: new Date('2024-01-07'),
  },
  {
    id: 'user-10',
    username: 'sneaker_scholar',
    displayName: 'Olivia Garcia',
    email: 'olivia@sneakergram.com',
    avatar: getAvatar(avatarSeeds[9]),
    bio: 'Sneaker historian | Educator 📚',
    shoeSize: '7',
    verified: true,
    verificationLevel: VerificationLevel.GOLD,
    followers: 11567,
    following: 678,
    collection: ['sneaker-36', 'sneaker-37'],
    wishlist: ['sneaker-38'],
    createdAt: new Date('2021-07-22'),
    updatedAt: new Date('2024-01-06'),
  },
  {
    id: 'user-11',
    username: 'airmax_addict',
    displayName: 'Ryan Park',
    email: 'ryan@sneakergram.com',
    avatar: getAvatar(avatarSeeds[10]),
    bio: 'Air Max 90 is life 💨',
    shoeSize: '10',
    verified: true,
    verificationLevel: VerificationLevel.ID,
    followers: 7823,
    following: 512,
    collection: ['sneaker-1', 'sneaker-5'],
    wishlist: ['sneaker-8'],
    createdAt: new Date('2022-05-10'),
    updatedAt: new Date('2024-01-05'),
  },
  {
    id: 'user-12',
    username: 'nb_collector',
    displayName: 'Jessica Kim',
    email: 'jessica@sneakergram.com',
    avatar: getAvatar(avatarSeeds[11]),
    bio: 'New Balance 990 series 🇺🇸',
    shoeSize: '7',
    verified: false,
    verificationLevel: VerificationLevel.EMAIL,
    followers: 4521,
    following: 321,
    collection: ['sneaker-15', 'sneaker-16'],
    wishlist: ['sneaker-17'],
    createdAt: new Date('2023-03-15'),
    updatedAt: new Date('2024-01-04'),
  },
  {
    id: 'user-13',
    username: 'travis_fan',
    displayName: 'Derek Williams',
    email: 'derek@sneakergram.com',
    avatar: getAvatar(avatarSeeds[12]),
    bio: 'Travis Scott collabs only 🌵',
    shoeSize: '11',
    verified: true,
    verificationLevel: VerificationLevel.GOLD,
    followers: 23456,
    following: 156,
    collection: ['sneaker-1', 'sneaker-2'],
    wishlist: ['sneaker-3'],
    createdAt: new Date('2021-08-20'),
    updatedAt: new Date('2024-01-03'),
  },
  {
    id: 'user-14',
    username: 'vintage_vibes',
    displayName: 'Amanda Foster',
    email: 'amanda@sneakergram.com',
    avatar: getAvatar(avatarSeeds[13]),
    bio: 'OG colorways only 🎨',
    shoeSize: '8',
    verified: false,
    verificationLevel: VerificationLevel.EMAIL,
    followers: 3456,
    following: 678,
    collection: ['sneaker-7', 'sneaker-8'],
    wishlist: ['sneaker-9'],
    createdAt: new Date('2023-01-05'),
    updatedAt: new Date('2024-01-02'),
  },
  {
    id: 'user-15',
    username: 'sneaker_plug',
    displayName: 'Kevin Zhang',
    email: 'kevin@sneakergram.com',
    avatar: getAvatar(avatarSeeds[14]),
    bio: 'Reseller | Best prices 💰',
    shoeSize: '10.5',
    verified: true,
    verificationLevel: VerificationLevel.ID,
    followers: 15678,
    following: 234,
    collection: ['sneaker-1', 'sneaker-2', 'sneaker-3'],
    wishlist: [],
    createdAt: new Date('2021-06-15'),
    updatedAt: new Date('2024-01-01'),
  },
];


// Generate Mock Sneakers with HIGH QUALITY images only
export const mockSneakers: Sneaker[] = [
  {
    id: 'sneaker-1',
    brand: 'Nike',
    model: 'Air Jordan 4',
    colorway: 'Black Cats',
    releaseDate: '2020-01-25',
    retailPrice: 190,
    marketValue: 350,
    images: [BEST_SNEAKER_IMAGES.blackCats, BEST_SNEAKER_IMAGES.jordanRetro],
    sizes: ['7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '11.5', '12', '13'],
    description: 'The Air Jordan 4 Black Cat features an all-black colorway with premium materials.',
    ownedByUsers: 4521,
    category: SneakerCategory.JORDAN,
  },
  {
    id: 'sneaker-2',
    brand: 'Nike',
    model: 'Air Force 1',
    colorway: 'White',
    releaseDate: '2022-06-15',
    retailPrice: 110,
    marketValue: 130,
    images: [BEST_SNEAKER_IMAGES.airForces1, BEST_SNEAKER_IMAGES.nikeAirForces],
    sizes: ['7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '11.5', '12', '13'],
    description: 'The classic Nike Air Force 1 in pristine white leather.',
    ownedByUsers: 8934,
    category: SneakerCategory.NIKE,
  },
  {
    id: 'sneaker-3',
    brand: 'Adidas',
    model: 'Superstar',
    colorway: 'Black/White',
    releaseDate: '2021-03-10',
    retailPrice: 100,
    marketValue: 95,
    images: [BEST_SNEAKER_IMAGES.adidasSuperstar, BEST_SNEAKER_IMAGES.adidas],
    sizes: ['7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '11.5', '12', '13'],
    description: 'The iconic Adidas Superstar with shell toe design.',
    ownedByUsers: 6234,
    category: SneakerCategory.ADIDAS,
  },
  {
    id: 'sneaker-4',
    brand: 'Nike',
    model: 'Air Jordan 1',
    colorway: 'Bred',
    releaseDate: '2019-11-29',
    retailPrice: 170,
    marketValue: 450,
    images: [BEST_SNEAKER_IMAGES.jordanBlackRed, BEST_SNEAKER_IMAGES.jordanBlue],
    sizes: ['7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '11.5', '12', '13'],
    description: 'The legendary Air Jordan 1 in the classic Bred colorway.',
    ownedByUsers: 3456,
    category: SneakerCategory.JORDAN,
  },
  {
    id: 'sneaker-5',
    brand: 'New Balance',
    model: '990v5',
    colorway: 'Grey',
    releaseDate: '2022-08-20',
    retailPrice: 185,
    marketValue: 220,
    images: [BEST_SNEAKER_IMAGES.newBalance1, BEST_SNEAKER_IMAGES.newBalancePerformance],
    sizes: ['7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '11.5', '12', '13'],
    description: 'The premium New Balance 990v5 Made in USA.',
    ownedByUsers: 2134,
    category: SneakerCategory.NEWBALANCE,
  },
  {
    id: 'sneaker-6',
    brand: 'Nike',
    model: 'Air Jordan 4',
    colorway: 'Pine Green',
    releaseDate: '2023-03-18',
    retailPrice: 225,
    marketValue: 380,
    images: [BEST_SNEAKER_IMAGES.jordanPineGreen, BEST_SNEAKER_IMAGES.jordanBlackYellow],
    sizes: ['7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '11.5', '12', '13'],
    description: 'Nike SB x Air Jordan 4 Pine Green collaboration.',
    ownedByUsers: 1876,
    category: SneakerCategory.JORDAN,
  },
  {
    id: 'sneaker-7',
    brand: 'Nike',
    model: 'Air Force 1',
    colorway: 'Red',
    releaseDate: '2023-01-10',
    retailPrice: 120,
    marketValue: 150,
    images: [BEST_SNEAKER_IMAGES.nikeRedForces, BEST_SNEAKER_IMAGES.nikePinks],
    sizes: ['7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '11.5', '12', '13'],
    description: 'Nike Air Force 1 in bold red colorway.',
    ownedByUsers: 3421,
    category: SneakerCategory.NIKE,
  },
  {
    id: 'sneaker-8',
    brand: 'Adidas',
    model: 'Forum',
    colorway: 'High White',
    releaseDate: '2022-09-05',
    retailPrice: 110,
    marketValue: 125,
    images: [BEST_SNEAKER_IMAGES.adidasForum, BEST_SNEAKER_IMAGES.adidasStand],
    sizes: ['7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '11.5', '12', '13'],
    description: 'The retro Adidas Forum High in clean white.',
    ownedByUsers: 2567,
    category: SneakerCategory.ADIDAS,
  },
  {
    id: 'sneaker-9',
    brand: 'Louis Vuitton',
    model: 'LV Trainer',
    colorway: 'Monogram',
    releaseDate: '2023-05-20',
    retailPrice: 1200,
    marketValue: 1500,
    images: [BEST_SNEAKER_IMAGES.lv1, BEST_SNEAKER_IMAGES.lv2],
    sizes: ['7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '11.5', '12', '13'],
    description: 'Luxury Louis Vuitton LV Trainer sneaker.',
    ownedByUsers: 456,
    category: SneakerCategory.OTHER,
  },
  {
    id: 'sneaker-10',
    brand: 'Nike',
    model: 'Air Jordan 1',
    colorway: 'Royal Blue',
    releaseDate: '2021-04-17',
    retailPrice: 170,
    marketValue: 320,
    images: [BEST_SNEAKER_IMAGES.jordanBlue, BEST_SNEAKER_IMAGES.jordanBlackRed],
    sizes: ['7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '11.5', '12', '13'],
    description: 'Air Jordan 1 High in iconic Royal Blue.',
    ownedByUsers: 5678,
    category: SneakerCategory.JORDAN,
  },
  {
    id: 'sneaker-11',
    brand: 'Nike',
    model: 'Air Jordan Retro',
    colorway: 'Chicago',
    releaseDate: '2020-02-08',
    retailPrice: 170,
    marketValue: 520,
    images: [BEST_SNEAKER_IMAGES.jordanRetro, BEST_SNEAKER_IMAGES.blackCats],
    sizes: ['7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '11.5', '12', '13'],
    description: 'The classic Air Jordan Retro in Chicago colors.',
    ownedByUsers: 4123,
    category: SneakerCategory.JORDAN,
  },
  {
    id: 'sneaker-12',
    brand: 'Nike',
    model: 'Air Jordan 1',
    colorway: 'Black/Yellow',
    releaseDate: '2022-07-23',
    retailPrice: 170,
    marketValue: 280,
    images: [BEST_SNEAKER_IMAGES.jordanBlackYellow, BEST_SNEAKER_IMAGES.jordanPineGreen],
    sizes: ['7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '11.5', '12', '13'],
    description: 'Air Jordan 1 in striking Black and Yellow.',
    ownedByUsers: 2890,
    category: SneakerCategory.JORDAN,
  },
  {
    id: 'sneaker-13',
    brand: 'Nike',
    model: 'Air Max Plus',
    colorway: 'Yellow/Black',
    releaseDate: '2023-09-15',
    retailPrice: 180,
    marketValue: 250,
    images: [BEST_SNEAKER_IMAGES.yellowBlackSneaker, BEST_SNEAKER_IMAGES.jordanBlackYellow],
    sizes: ['7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '11.5', '12', '13'],
    description: 'The Nike Air Max Plus in bold Yellow and Black colorway.',
    ownedByUsers: 1567,
    category: SneakerCategory.NIKE,
  },
];


// Generate Mock Posts - Instagram-like feed with HIGH QUALITY images
export const mockPosts: Post[] = [
  {
    id: 'post-1',
    userId: 'user-1',
    type: PostType.COLLECTION,
    images: [BEST_SNEAKER_IMAGES.blackCats, BEST_SNEAKER_IMAGES.jordanRetro],
    caption: 'My Jordan 4 collection is finally complete! 🔥 Black Cats are unmatched',
    sneakerTags: ['sneaker-1'],
    likes: 1234,
    comments: [{ id: 'c1', postId: 'post-1', userId: 'user-2', text: 'Fire collection! 🔥', createdAt: getRandomPastDate(1) }],
    likedBy: ['user-2', 'user-3', 'user-4'],
    savedBy: ['user-5'],
    canBid: true,
    bidSneakerId: 'sneaker-1',
    createdAt: getRandomPastDate(1),
    updatedAt: getRandomPastDate(1),
  },
  {
    id: 'post-2',
    userId: 'user-2',
    type: PostType.PICKUP,
    images: [BEST_SNEAKER_IMAGES.airForces1, BEST_SNEAKER_IMAGES.nikeAirForces],
    caption: 'Just picked up these crispy Air Force 1s! 👟 Classic never dies',
    sneakerTags: ['sneaker-2'],
    likes: 892,
    comments: [],
    likedBy: ['user-1', 'user-3'],
    savedBy: [],
    canBid: false,
    createdAt: getRandomPastDate(2),
    updatedAt: getRandomPastDate(2),
  },
  {
    id: 'post-3',
    userId: 'user-3',
    type: PostType.FITCHECK,
    images: [BEST_SNEAKER_IMAGES.adidasSuperstar, BEST_SNEAKER_IMAGES.adidasForum, BEST_SNEAKER_IMAGES.adidas],
    caption: 'Adidas rotation for the week 💯 Three stripes gang',
    sneakerTags: ['sneaker-3', 'sneaker-8'],
    likes: 2341,
    comments: [{ id: 'c2', postId: 'post-3', userId: 'user-1', text: 'Clean fit!', createdAt: getRandomPastDate(2) }],
    likedBy: ['user-1', 'user-2', 'user-4', 'user-5'],
    savedBy: ['user-6'],
    canBid: true,
    bidSneakerId: 'sneaker-3',
    createdAt: getRandomPastDate(3),
    updatedAt: getRandomPastDate(3),
  },
  {
    id: 'post-4',
    userId: 'user-5',
    type: PostType.PICKUP,
    images: [BEST_SNEAKER_IMAGES.nikeRedForces, BEST_SNEAKER_IMAGES.nikePinks],
    caption: 'Finally got my hands on these! 🎯 Red forces hit different',
    sneakerTags: ['sneaker-7'],
    likes: 1876,
    comments: [{ id: 'c3', postId: 'post-4', userId: 'user-3', text: 'Where did you cop?', createdAt: getRandomPastDate(4) }],
    likedBy: ['user-1', 'user-3', 'user-6'],
    savedBy: ['user-2'],
    canBid: true,
    bidSneakerId: 'sneaker-7',
    createdAt: getRandomPastDate(4),
    updatedAt: getRandomPastDate(4),
  },
  {
    id: 'post-5',
    userId: 'user-9',
    type: PostType.FITCHECK,
    images: [BEST_SNEAKER_IMAGES.jordanBlackRed, BEST_SNEAKER_IMAGES.jordanBlue],
    caption: 'Hype beast mode activated 💪 Jordan 1 Bred vs Royal',
    sneakerTags: ['sneaker-4', 'sneaker-10'],
    likes: 3456,
    comments: [{ id: 'c4', postId: 'post-5', userId: 'user-1', text: 'Straight fire! 🔥', createdAt: getRandomPastDate(1) }],
    likedBy: ['user-1', 'user-2', 'user-3', 'user-4', 'user-5'],
    savedBy: ['user-6', 'user-7'],
    canBid: true,
    bidSneakerId: 'sneaker-4',
    createdAt: getRandomPastDate(5),
    updatedAt: getRandomPastDate(5),
  },
  {
    id: 'post-6',
    userId: 'user-11',
    type: PostType.COLLECTION,
    images: [BEST_SNEAKER_IMAGES.newBalance1, BEST_SNEAKER_IMAGES.newBalancePerformance],
    caption: 'New Balance 990 rotation 💨 Made in USA quality',
    sneakerTags: ['sneaker-5'],
    likes: 987,
    comments: [],
    likedBy: ['user-2', 'user-4'],
    savedBy: [],
    canBid: false,
    createdAt: getRandomPastDate(6),
    updatedAt: getRandomPastDate(6),
  },
  {
    id: 'post-7',
    userId: 'user-13',
    type: PostType.PICKUP,
    images: [BEST_SNEAKER_IMAGES.jordanPineGreen, BEST_SNEAKER_IMAGES.jordanBlackYellow],
    caption: 'Jordan 4 Pine Green secured 🌵 SB collab is insane',
    sneakerTags: ['sneaker-6', 'sneaker-12'],
    likes: 5678,
    comments: [{ id: 'c5', postId: 'post-7', userId: 'user-9', text: 'W!', createdAt: getRandomPastDate(1) }],
    likedBy: ['user-1', 'user-2', 'user-3', 'user-9'],
    savedBy: ['user-5', 'user-7', 'user-10'],
    canBid: true,
    bidSneakerId: 'sneaker-6',
    createdAt: getRandomPastDate(7),
    updatedAt: getRandomPastDate(7),
  },
  {
    id: 'post-8',
    userId: 'user-12',
    type: PostType.COLLECTION,
    images: [BEST_SNEAKER_IMAGES.adidasForum, BEST_SNEAKER_IMAGES.adidasStand],
    caption: 'Adidas Forum collection 🏀 Retro vibes only',
    sneakerTags: ['sneaker-8'],
    likes: 654,
    comments: [],
    likedBy: ['user-4', 'user-7'],
    savedBy: ['user-1'],
    canBid: false,
    createdAt: getRandomPastDate(8),
    updatedAt: getRandomPastDate(8),
  },
  {
    id: 'post-9',
    userId: 'user-15',
    type: PostType.PICKUP,
    images: [BEST_SNEAKER_IMAGES.lv1, BEST_SNEAKER_IMAGES.lv2],
    caption: 'Luxury heat 🔥💎 LV Trainer finally in hand',
    sneakerTags: ['sneaker-9'],
    likes: 8765,
    comments: [{ id: 'c6', postId: 'post-9', userId: 'user-13', text: 'Grails!', createdAt: getRandomPastDate(1) }],
    likedBy: ['user-1', 'user-2', 'user-3', 'user-9', 'user-13'],
    savedBy: ['user-5', 'user-7'],
    canBid: false,
    createdAt: getRandomPastDate(9),
    updatedAt: getRandomPastDate(9),
  },
  {
    id: 'post-10',
    userId: 'user-7',
    type: PostType.FITCHECK,
    images: [BEST_SNEAKER_IMAGES.jordanRetro, BEST_SNEAKER_IMAGES.blackCats],
    caption: 'Jordan Retro vibes today 🏃 Which one you rocking?',
    sneakerTags: ['sneaker-11', 'sneaker-1'],
    likes: 432,
    comments: [],
    likedBy: ['user-3', 'user-11'],
    savedBy: [],
    canBid: false,
    createdAt: getRandomPastDate(10),
    updatedAt: getRandomPastDate(10),
  },
  {
    id: 'post-11',
    userId: 'user-6',
    type: PostType.PICKUP,
    images: [BEST_SNEAKER_IMAGES.yellowBlackSneaker, BEST_SNEAKER_IMAGES.jordanBlackYellow],
    caption: 'Yellow and black attack! 🐝 Air Max Plus finally copped',
    sneakerTags: ['sneaker-13'],
    likes: 2156,
    comments: [{ id: 'c7', postId: 'post-11', userId: 'user-9', text: 'Those are crazy! 🔥', createdAt: getRandomPastDate(1) }],
    likedBy: ['user-1', 'user-9', 'user-13', 'user-15'],
    savedBy: ['user-2', 'user-7'],
    canBid: true,
    bidSneakerId: 'sneaker-13',
    createdAt: getRandomPastDate(2),
    updatedAt: getRandomPastDate(2),
  },
];


// Generate Mock Listings with HIGH QUALITY images
export const mockListings: Listing[] = [
  { id: 'listing-1', sellerId: 'user-1', sneakerId: 'sneaker-1', images: [BEST_SNEAKER_IMAGES.blackCats, BEST_SNEAKER_IMAGES.jordanRetro], size: '10.5', condition: 9, price: 350, type: ListingType.SALE, verified: true, status: ListingStatus.ACTIVE, createdAt: getRandomPastDate(1), updatedAt: getRandomPastDate(1) },
  { id: 'listing-2', sellerId: 'user-2', sneakerId: 'sneaker-2', images: [BEST_SNEAKER_IMAGES.airForces1, BEST_SNEAKER_IMAGES.nikeAirForces], size: '9', condition: 10, price: 130, type: ListingType.SALE, verified: true, status: ListingStatus.ACTIVE, createdAt: getRandomPastDate(2), updatedAt: getRandomPastDate(2) },
  { id: 'listing-3', sellerId: 'user-3', sneakerId: 'sneaker-3', images: [BEST_SNEAKER_IMAGES.adidasSuperstar, BEST_SNEAKER_IMAGES.adidas], size: '11', condition: 8, price: 95, rentPrice: 40, rentDeposit: 150, rentAvailableFrom: new Date(), rentAvailableTo: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000), type: ListingType.RENT, verified: false, status: ListingStatus.ACTIVE, createdAt: getRandomPastDate(3), updatedAt: getRandomPastDate(3) },
  { id: 'listing-4', sellerId: 'user-5', sneakerId: 'sneaker-4', images: [BEST_SNEAKER_IMAGES.jordanBlackRed, BEST_SNEAKER_IMAGES.jordanBlue], size: '10', condition: 9, price: 450, currentBid: 380, bidHistory: [{ id: 'bid-1', listingId: 'listing-4', userId: 'user-9', amount: 380, createdAt: getRandomPastDate(1) }], bidEndTime: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000), type: ListingType.AUCTION, verified: true, status: ListingStatus.ACTIVE, createdAt: getRandomPastDate(4), updatedAt: getRandomPastDate(4) },
  { id: 'listing-5', sellerId: 'user-7', sneakerId: 'sneaker-5', images: [BEST_SNEAKER_IMAGES.newBalance1, BEST_SNEAKER_IMAGES.newBalancePerformance], size: '9.5', condition: 10, price: 220, type: ListingType.SALE, verified: true, status: ListingStatus.ACTIVE, createdAt: getRandomPastDate(5), updatedAt: getRandomPastDate(5) },
  { id: 'listing-6', sellerId: 'user-9', sneakerId: 'sneaker-6', images: [BEST_SNEAKER_IMAGES.jordanPineGreen, BEST_SNEAKER_IMAGES.jordanBlackYellow], size: '11', condition: 9, price: 380, type: ListingType.SALE, verified: true, status: ListingStatus.ACTIVE, createdAt: getRandomPastDate(6), updatedAt: getRandomPastDate(6) },
  { id: 'listing-7', sellerId: 'user-11', sneakerId: 'sneaker-7', images: [BEST_SNEAKER_IMAGES.nikeRedForces, BEST_SNEAKER_IMAGES.nikePinks], size: '10', condition: 8, price: 150, rentPrice: 35, rentDeposit: 120, rentAvailableFrom: new Date(), rentAvailableTo: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000), type: ListingType.RENT, verified: false, status: ListingStatus.ACTIVE, createdAt: getRandomPastDate(7), updatedAt: getRandomPastDate(7) },
  { id: 'listing-8', sellerId: 'user-13', sneakerId: 'sneaker-8', images: [BEST_SNEAKER_IMAGES.adidasForum, BEST_SNEAKER_IMAGES.adidasStand], size: '10.5', condition: 10, price: 125, currentBid: 100, bidHistory: [{ id: 'bid-2', listingId: 'listing-8', userId: 'user-15', amount: 90, createdAt: getRandomPastDate(2) }, { id: 'bid-3', listingId: 'listing-8', userId: 'user-1', amount: 100, createdAt: getRandomPastDate(1) }], bidEndTime: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000), type: ListingType.AUCTION, verified: true, status: ListingStatus.ACTIVE, createdAt: getRandomPastDate(8), updatedAt: getRandomPastDate(8) },
  { id: 'listing-9', sellerId: 'user-15', sneakerId: 'sneaker-9', images: [BEST_SNEAKER_IMAGES.lv1, BEST_SNEAKER_IMAGES.lv2], size: '10', condition: 10, price: 1500, type: ListingType.SALE, verified: true, status: ListingStatus.ACTIVE, createdAt: getRandomPastDate(9), updatedAt: getRandomPastDate(9) },
  { id: 'listing-10', sellerId: 'user-6', sneakerId: 'sneaker-10', images: [BEST_SNEAKER_IMAGES.jordanBlue, BEST_SNEAKER_IMAGES.jordanBlackRed], size: '9', condition: 8, price: 320, type: ListingType.SALE, verified: false, status: ListingStatus.ACTIVE, createdAt: getRandomPastDate(10), updatedAt: getRandomPastDate(10) },
  { id: 'listing-11', sellerId: 'user-4', sneakerId: 'sneaker-13', images: [BEST_SNEAKER_IMAGES.yellowBlackSneaker, BEST_SNEAKER_IMAGES.jordanBlackYellow], size: '10', condition: 10, price: 250, type: ListingType.SALE, verified: true, status: ListingStatus.ACTIVE, createdAt: getRandomPastDate(3), updatedAt: getRandomPastDate(3) },
];


// Generate Mock Conversations - More chats like Instagram
export const mockConversations: Conversation[] = [
  {
    id: 'conv-1',
    participants: ['user-1', 'user-2'],
    lastMessage: 'Thanks! Let me know if you want to trade',
    lastMessageTime: getRandomMinutesAgo(5),
    unreadCount: 2,
    listingContext: 'listing-1',
  },
  {
    id: 'conv-2',
    participants: ['user-1', 'user-3'],
    lastMessage: 'Is this still available?',
    lastMessageTime: getRandomMinutesAgo(30),
    unreadCount: 1,
  },
  {
    id: 'conv-3',
    participants: ['user-1', 'user-5'],
    lastMessage: 'Great collection! 🔥',
    lastMessageTime: getRandomMinutesAgo(60),
    unreadCount: 0,
  },
  {
    id: 'conv-4',
    participants: ['user-1', 'user-9'],
    lastMessage: 'Can you do $200?',
    lastMessageTime: getRandomMinutesAgo(120),
    unreadCount: 3,
  },
  {
    id: 'conv-5',
    participants: ['user-1', 'user-11'],
    lastMessage: 'Shipped! Tracking sent 📦',
    lastMessageTime: getRandomMinutesAgo(180),
    unreadCount: 0,
  },
  {
    id: 'conv-6',
    participants: ['user-1', 'user-13'],
    lastMessage: 'Those Travis Scotts are 🔥',
    lastMessageTime: getRandomMinutesAgo(240),
    unreadCount: 1,
  },
  {
    id: 'conv-7',
    participants: ['user-1', 'user-7'],
    lastMessage: 'Deal! PayPal or Venmo?',
    lastMessageTime: getRandomMinutesAgo(300),
    unreadCount: 0,
  },
  {
    id: 'conv-8',
    participants: ['user-1', 'user-15'],
    lastMessage: 'I have size 10.5 in stock',
    lastMessageTime: getRandomMinutesAgo(400),
    unreadCount: 2,
  },
];


// Generate Mock Messages
export const mockMessages: Message[] = [
  { id: 'msg-1', conversationId: 'conv-1', senderId: 'user-2', receiverId: 'user-1', text: 'Hey! Interested in your Jordan 1s', type: MessageType.TEXT, createdAt: getRandomMinutesAgo(10), read: true },
  { id: 'msg-2', conversationId: 'conv-1', senderId: 'user-1', receiverId: 'user-2', text: 'Thanks! Let me know if you want to trade', type: MessageType.TEXT, createdAt: getRandomMinutesAgo(5), read: false },
  { id: 'msg-3', conversationId: 'conv-2', senderId: 'user-3', receiverId: 'user-1', text: 'Is this still available?', type: MessageType.TEXT, createdAt: getRandomMinutesAgo(30), read: false },
  { id: 'msg-4', conversationId: 'conv-3', senderId: 'user-5', receiverId: 'user-1', text: 'Great collection! 🔥', type: MessageType.TEXT, createdAt: getRandomMinutesAgo(60), read: true },
  { id: 'msg-5', conversationId: 'conv-4', senderId: 'user-9', receiverId: 'user-1', text: 'What size are these?', type: MessageType.TEXT, createdAt: getRandomMinutesAgo(150), read: true },
  { id: 'msg-6', conversationId: 'conv-4', senderId: 'user-1', receiverId: 'user-9', text: 'Size 10.5, DS condition', type: MessageType.TEXT, createdAt: getRandomMinutesAgo(140), read: true },
  { id: 'msg-7', conversationId: 'conv-4', senderId: 'user-9', receiverId: 'user-1', text: 'Can you do $200?', type: MessageType.TEXT, createdAt: getRandomMinutesAgo(120), read: false },
  { id: 'msg-8', conversationId: 'conv-5', senderId: 'user-1', receiverId: 'user-11', text: 'Shipped! Tracking sent 📦', type: MessageType.TEXT, createdAt: getRandomMinutesAgo(180), read: true },
  { id: 'msg-9', conversationId: 'conv-6', senderId: 'user-13', receiverId: 'user-1', text: 'Those Travis Scotts are 🔥', type: MessageType.TEXT, createdAt: getRandomMinutesAgo(240), read: false },
  { id: 'msg-10', conversationId: 'conv-7', senderId: 'user-7', receiverId: 'user-1', text: 'Deal! PayPal or Venmo?', type: MessageType.TEXT, createdAt: getRandomMinutesAgo(300), read: true },
  { id: 'msg-11', conversationId: 'conv-8', senderId: 'user-15', receiverId: 'user-1', text: 'I have size 10.5 in stock', type: MessageType.TEXT, createdAt: getRandomMinutesAgo(400), read: false },
];


// Generate Mock Notifications - Instagram-like activity
export const mockNotifications: Notification[] = [
  { id: 'n1', userId: 'user-1', type: NotificationType.LIKE, actorId: 'user-2', postId: 'post-1', message: 'kickz_queen liked your post', read: false, createdAt: getRandomMinutesAgo(2) },
  { id: 'n2', userId: 'user-1', type: NotificationType.LIKE, actorId: 'user-3', postId: 'post-1', message: 'yeezy_fanatic liked your post', read: false, createdAt: getRandomMinutesAgo(5) },
  { id: 'n3', userId: 'user-1', type: NotificationType.COMMENT, actorId: 'user-5', postId: 'post-1', message: 'sole_collector commented: "Fire! 🔥"', read: false, createdAt: getRandomMinutesAgo(10) },
  { id: 'n4', userId: 'user-1', type: NotificationType.FOLLOW, actorId: 'user-9', message: 'hype_beast started following you', read: false, createdAt: getRandomMinutesAgo(15) },
  { id: 'n5', userId: 'user-1', type: NotificationType.LIKE, actorId: 'user-11', postId: 'post-1', message: 'airmax_addict liked your post', read: true, createdAt: getRandomMinutesAgo(30) },
  { id: 'n6', userId: 'user-1', type: NotificationType.FOLLOW, actorId: 'user-13', message: 'travis_fan started following you', read: true, createdAt: getRandomMinutesAgo(45) },
  { id: 'n7', userId: 'user-1', type: NotificationType.BID, actorId: 'user-7', listingId: 'listing-1', message: 'boost_life placed a bid on your listing', read: true, createdAt: getRandomMinutesAgo(60) },
  { id: 'n8', userId: 'user-1', type: NotificationType.COMMENT, actorId: 'user-12', postId: 'post-1', message: 'nb_collector commented: "Need these!"', read: true, createdAt: getRandomMinutesAgo(90) },
  { id: 'n9', userId: 'user-1', type: NotificationType.LIKE, actorId: 'user-14', postId: 'post-1', message: 'vintage_vibes liked your post', read: true, createdAt: getRandomMinutesAgo(120) },
  { id: 'n10', userId: 'user-1', type: NotificationType.FOLLOW, actorId: 'user-15', message: 'sneaker_plug started following you', read: true, createdAt: getRandomMinutesAgo(180) },
  { id: 'n11', userId: 'user-1', type: NotificationType.PRICEDROP, listingId: 'listing-5', message: 'Price dropped on a sneaker in your wishlist', read: true, createdAt: getRandomMinutesAgo(240) },
  { id: 'n12', userId: 'user-1', type: NotificationType.LIKE, actorId: 'user-6', postId: 'post-1', message: 'dunk_master and 5 others liked your post', read: true, createdAt: getRandomMinutesAgo(300) },
];


// Generate Mock Services
export const mockServices: Service[] = [
  { id: 'service-1', name: 'Sneaker Authentication', description: 'Professional authentication service', icon: 'shield-check', price: 25, turnaroundTime: '2-3 days', category: ServiceCategory.AUTHENTICATION },
  { id: 'service-2', name: 'Premium Rental', description: 'Rent high-end sneakers', icon: 'calendar', price: 50, turnaroundTime: 'Flexible', category: ServiceCategory.RENTAL },
  { id: 'service-3', name: 'Deep Cleaning', description: 'Professional cleaning service', icon: 'sparkles', price: 35, turnaroundTime: '1-2 days', category: ServiceCategory.CLEANING },
  { id: 'service-4', name: 'Restoration', description: 'Expert restoration service', icon: 'wrench', price: 75, turnaroundTime: '5-7 days', category: ServiceCategory.RESTORATION },
];

// Helper functions
export function getUserById(userId: string): User | undefined {
  return mockUsers.find(user => user.id === userId);
}

export function getSneakerById(sneakerId: string): Sneaker | undefined {
  return mockSneakers.find(sneaker => sneaker.id === sneakerId);
}

export function getPostById(postId: string): Post | undefined {
  return mockPosts.find(post => post.id === postId);
}

export function getListingById(listingId: string): Listing | undefined {
  return mockListings.find(listing => listing.id === listingId);
}

export const mockData = {
  users: mockUsers,
  sneakers: mockSneakers,
  posts: mockPosts,
  listings: mockListings,
  conversations: mockConversations,
  messages: mockMessages,
  notifications: mockNotifications,
  services: mockServices,
};
